# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demo1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit', '~> 5.6.0'

  # Pods for demo1

  target 'demo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'demo1UITests' do
    # Pods for testing
  end

end
